kubernetesClusterDomain: cluster.local
operator:
  keycloakOperator:
    env:
      relatedImageKeycloak: quay.io/keycloak/keycloak:23.0.0
    image:
      repository: quay.io/keycloak/keycloak-operator
      tag: 23.0.0
    imagePullPolicy: Always
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  replicas: 1
  serviceAccount:
    annotations:
      app.quarkus.io/build-timestamp: 2023-11-23 - 15:10:01 +0000
  type: ClusterIP
