kubernetesClusterDomain: cluster.local
operator:
  keycloakOperator:
    env:
      relatedImageKeycloak: quay.io/keycloak/keycloak:26.0.0
    image:
      repository: quay.io/keycloak/keycloak-operator
      tag: 26.0.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 700m
        memory: 450Mi
      requests:
        cpu: 300m
        memory: 450Mi
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  replicas: 1
  serviceAccount:
    annotations:
      app.quarkus.io/build-timestamp: 2024-10-04 - 07:10:18 +0000
      app.quarkus.io/quarkus-version: 3.15.1
      app.quarkus.io/vcs-uri: https://github.com/keycloak/keycloak.git
  type: ClusterIP
