apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    app.quarkus.io/build-timestamp: 2023-08-17 - 13:17:19 +0000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-realmimportcontroller-cluster-role
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.keycloak.org
  resources:
  - keycloakrealmimports
  - keycloakrealmimports/status
  - keycloakrealmimports/finalizers
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-controller-cluster-role
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.keycloak.org
  resources:
  - keycloaks
  - keycloaks/status
  - keycloaks/finalizers
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator-role
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator-role-binding
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "keycloak-operator.fullname" . }}-operator-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "keycloak-operator.fullname" . }}-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-realmimportcontroller-role-binding
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "keycloak-operator.fullname" . }}-realmimportcontroller-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "keycloak-operator.fullname" . }}-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-controller-role-binding
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "keycloak-operator.fullname" . }}-controller-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "keycloak-operator.fullname" . }}-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator-view
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: '{{ include "keycloak-operator.fullname" . }}-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    app.quarkus.io/build-timestamp: 2023-08-17 - 13:17:19 +0000
spec:
  type: {{ .Values.operator.type }}
  selector:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: 22.0.1
  {{- include "keycloak-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.operator.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    app.quarkus.io/build-timestamp: 2023-08-17 - 13:17:19 +0000
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
      app.kubernetes.io/version: 22.0.1
    {{- include "keycloak-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: keycloak-operator
        app.kubernetes.io/version: 22.0.1
      {{- include "keycloak-operator.selectorLabels" . | nindent 8 }}
      annotations:
        app.quarkus.io/build-timestamp: 2023-08-17 - 13:17:19 +0000
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_KEYCLOAK_IMAGE
          value: {{ quote .Values.operator.keycloakOperator.env.operatorKeycloakImage }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.operator.keycloakOperator.image.repository }}:{{ .Values.operator.keycloakOperator.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.operator.keycloakOperator.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: keycloak-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/started
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: {{ include "keycloak-operator.fullname" . }}-operator